# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Colin Cammarano/Workspace/USC/EE-454/EE-454-Project/Implementation/Vivado/EE454_Final_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Colin Cammarano/Workspace/USC/EE-454/EE-454-Project/Implementation/Vivado/EE454_Final_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Colin Cammarano/Workspace/USC/EE-454/EE-454-Project/Implementation/Vivado/EE454_Final_Project.srcs/sources_1/m_port_ultra_quickhull.v}
  {C:/Users/Colin Cammarano/Workspace/USC/EE-454/EE-454-Project/Implementation/Vivado/EE454_Final_Project.srcs/sources_1/m_port_ultra_top.v}
  {C:/Users/Colin Cammarano/Workspace/USC/EE-454/EE-454-Project/Implementation/Vivado/EE454_Final_Project.srcs/sources_1/m_port_ultra.v}
  {C:/Users/Colin Cammarano/Workspace/USC/EE-454/EE-454-Project/Implementation/Vivado/EE454_Final_Project.srcs/sources_1/m_port_ultra_dispatcher.v}
  {C:/Users/Colin Cammarano/Workspace/USC/EE-454/EE-454-Project/Implementation/Vivado/EE454_Final_Project.srcs/sources_1/m_port_ultra_processor_array.v}
}
read_xdc {{C:/Users/Colin Cammarano/Workspace/USC/EE-454/EE-454-Project/Implementation/Vivado/EE454_Final_Project.srcs/constrs_1/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Colin Cammarano/Workspace/USC/EE-454/EE-454-Project/Implementation/Vivado/EE454_Final_Project.srcs/constrs_1/Nexys4DDR_Master.xdc}}]

synth_design -top m_port_ultra_top -part xc7a100tcsg324-1
write_checkpoint -noxdef m_port_ultra_top.dcp
catch { report_utilization -file m_port_ultra_top_utilization_synth.rpt -pb m_port_ultra_top_utilization_synth.pb }
